# Generated by Django 2.1.10 on 2019-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_auto_20190724_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_reseller',
            new_name='is_reseller',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='reseller location'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=33, verbose_name='phone number'),
        ),
    ]
